<?php

// Color option
Redux::setSection('appart_opt', array(
	'title'     => esc_html__('Colors', 'appart'),
	'id'        => 'color',
	'icon'      => 'dashicons dashicons-admin-appearance',
	'fields'    => array(
		array(
			'id'          => 'accent-color',
			'title'       => esc_html__('Accent color', 'appart'),
			'subtitle'    => esc_html__( 'Pick the color scheme for the whole website (default: #00bade)', 'appart' ),
			'type'        => 'color',
			'output'      => array(
				'color'    =>  '
				    .more_features .media .media-left i,
				    .sale_product_item.pr_grid .pr_details h5:hover,
				    .product-categories li a:before,
				    .product-categories .cat-item > a:hover,
				    .demo-video .video-promo a:hover,
				    .price-icon i, .appart-search .home_btn,
				    .purchase-btn, .features-area-six .feature-five-item .round,
				    .features-area-six .feature-five-item .round2 i:before,
				    .features_content_three .media .media-left .icon,
				    .footer-top .footer_sidebar .widget.about_us_widget .social_icon li:hover i,
				    .footer-top .footer_sidebar .widget.widget_contact ul li .fleft a:hover,
				    .footer-top .footer_sidebar .widget.widget_instagram span a:hover,
				    .footer-top .footer_sidebar .widget.widget_twitter .tweets li .tweets-text a:hover,
				    .description_tab.nav-item.active a, .additional_information_tab.nav-item.active a, 
				    .reviews_tab.nav-item.active a, .footer_bottom a:hover,
				    .promo-button .banner_btn,
				    .play-btn, .apps_button a,
				    .team_member:hover h2,
				    .promo-inner-right .overview-details .learn-btn-two,
				    a:hover, .ex_features_item i,
				    .hero-content .banner_btn.btn-transparent:hover,
				    .learn_btn, .try:hover,
				    .apps_button.white a:hover,
				    .hero-content .banner_btn.btn-white,
				    .navbar-expand-lg.navbar .navbar-nav li.submenu .dropdown-menu li:hover > a,
				    .sub_btn, .b_features_icon,
				    .post-widget .media .media-body ul li a:hover i,
				    .post-widget .media .media-body ul li a:hover,
				    .read-more-btn, .tweets-widget .tweets li a:hover,
				    .categories-widget .c-list li a:hover,
				    .read-more-btn:hover,
				    .blog-section .blog-items:hover h2,
				    .post-widget .media .media-body .tn_tittle:hover,
				    .blog-section .blog-items .post-info li a:hover,
				    .post_box_four .blog-text .date li a:hover,
				    .post_box .blog-text:hover a.read_btn,
				    .sidebar-widget ul li a:hover,
				    .navbar-expand-lg.navbar.shrink .get-btn,
				    .price_box_two:hover .rate,
				    .price_box_two .purchase_btn_two,
				    .b_features_item:hover h3,
				    .testimonial_area_two .carousel-control-prev:hover, 
				    .testimonial_area_two .carousel-control-next:hover,
				    .navbar-expand-lg.navbar.shrink .navbar-nav .nav-item a.active,
				    .navbar-expand-lg.navbar.shrink .navbar-nav .nav-item.current-menu-item>a,
				    .reviews_tab.nav-item.active a,
                    .navbar-expand-lg.navbar.shrink .navbar-nav .nav-item a:hover
				    ',
				'background'    => '
				    .testimonial-area .slick-dots li.slick-active button,
				    .product_details .cart_button .cart_btn,
				    .tinv-wraper.tinv-wishlist:hover,
				    .additional_information_tab.nav-item.active a,
				    .woocommerce #review_form #respond p input,
				    .woocommerce nav.woocommerce-pagination ul li a:focus, .woocommerce nav.woocommerce-pagination ul li a:hover,
                    .woocommerce nav.woocommerce-pagination ul li span.current,
                    .pagination a:hover, .pagination a.active,
				    .navbar-expand-lg.navbar.shrink .navbar-nav li a span.cart,
				    .demo-video .video-promo a, .tab_content a,
				    .color-b:before, .apps_button a:hover,
				    .owl-dots .owl-dot.active,
				    .team_member .content .social a:hover,
				    .promo-inner-right .overview-details .learn-btn-two:hover,
				    .price .pricing-box.active:hover .purchase-btn,
				    .learn_btn:hover, .price .pricing-box:hover .purchase-btn,
				    .learn-btn-two:hover, .learn-btn-two,
				    .features-area3 .features-tab li a:hover, .features-area3 .features-tab li a:focus,
				    .learn-btn-two, .search .page-content a.home_btn:hover, 
				    .appart-search .home_btn:hover, 
				    .features-area3 .features-tab li a.active,
				    .appart-search .form-wrapper .btn, .price_icon:before, .sub_btn:hover
				    ',
				'border-color'  => '
				    .demo-video .video-promo a:hover,
				    .apps_button a, .play-btn,
				    .learn_btn, .owl-dots .owl-dot,
				    .features-area3 .features-tab li a.active,
				    .features-area3 .features-tab li a:hover, .features-area3 .features-tab li a:focus,
				    .appart-search .home_btn, .search .page-content a.home_btn, 
				    .sub_btn, .b_features_icon, .app-details .app-icon, 
				    .woocommerce nav.woocommerce-pagination ul li a:focus, .woocommerce nav.woocommerce-pagination ul li a:hover,
                    .woocommerce nav.woocommerce-pagination ul li span.current,
                    .pagination a:hover, .pagination a.active,
				    .price_box_two .purchase_btn_two, .navbar-expand-lg.navbar.shrink .get-btn'
			),
			'default'   => '#00bade'
		),
        array(
            'id'          => 'accent_gradient',
            'type'        => 'color_gradient',
            'title'       => esc_html__( 'Accent gradient color', 'appart' ),
            'default'     => array(
                'from' => 'rgb(0,186,222)',
                'to' => 'rgb(74,119,244)',
            ),
        ),
	)
));